modLoader="javafml"
loaderVersion="[40,)"
license="Apache"

[[mods]]
modId="combatradar"
version="1.3"
displayName="CombatRadar"
credits="Thanks TealNerd for CivRadar"
authors="Aleksey Terzi"
description='''

'''

[[dependencies.combatradar]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.combatradar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="CLIENT"
